name: "Build and Publish Docker Image"

on:
  workflow_dispatch:
  schedule:
    # Run at 20:00 on every 29th day-of-month.
    - cron: "0 20 */29 * *"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }} # Switch for ${{ secrets.DOCKERHUB_USER }} when using Dockerhub
          password: ${{ secrets.GITHUB_TOKEN }} # Switch for ${{ secrets.DOCKERHUB_PASS }} when using Dockerhub

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule,pattern={{date 'YYYY.MM.DD'}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          flavor: latest=auto

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./one-container/pihole-unbound
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Optional, taking automatic build in to account, use latest to current date
          #build-args: |
          #  PIHOLE_VERION=${{ vars.PIHOLE_VERSION }}
